#!/bin/bash

if [ "${1:-}" = 'id' ]; then
    if [ ! -f /data/uuid.txt ]; then
        cat /proc/sys/kernel/random/uuid > /data/uuid.txt
    fi
    uuid=$(cat /data/uuid.txt)
    serial=$(cat /sys/class/net/$(ip route get 8.8.8.8 | grep -Po '(?<=(dev ))(\S+)')/address | sed 's/://g')

    # echo "board.sysid=0xb719" # UVC_NVR
    # echo "board.sysid=0xe970" # UCK_G2_PLUS
    # echo "board.sysid=0xea13" # UDM_SE
    # echo "board.sysid=0xea15" # UDM_PRO
    echo "board.sysid=0xea16" # UNVR4
    # echo "board.sysid=0xea1a" # UNVR4
    # echo "board.sysid=0xea20" # UNVR_PRO
    # echo "board.sysid=0xea3f" # ENVR
    # echo "board.sysid=0xea36" # UDMPROMAX
    # echo "board.sysid=0xea2a" # UDW
    # echo "board.sysid=0xa6ca" # UCGMAX
    # echo "board.sysid=0xa6d0" # UCGFIBER
    # echo "board.sysid=0xffff" # MAC_OS
    # echo "board.sysid=0xa6aa" # UDR7

    echo "board.name=UniFi Network Video Recorder"
    echo "board.shortname=UNVR"
    echo "board.subtype="
    echo "board.reboot=30"
    echo "board.upgrade=310"
    echo "board.cpu.id=00000000-00000000"
    echo "board.uuid=${uuid}"
    echo "board.bom=1"
    echo "board.hwrev=1"
    echo "board.serialno=${serial}"
    echo "board.qrid=sTpBUR"
fi
