#!/bin/bash

if [ "${1:-}" = 'id' ]; then
    if [ ! -f /data/uuid.txt ]; then
        cat /proc/sys/kernel/random/uuid > /data/uuid.txt
    fi
    uuid=$(cat /data/uuid.txt)
    serial=$(cat /sys/class/net/$(ip route get 8.8.8.8 | grep -Po '(?<=(dev ))(\S+)')/address | sed 's/://g')

    if [ -f /etc/default/device ]; then
        DEVICE="$(tr -d '-n' < /etc/default/device)"
    fi
    case "${DEVICE:-UNVR}" in
        'UNVR')
            echo "board.sysid=0xea16" # UNVR4 - default
            # echo "board.sysid=0xea1a" # UNVR4 - works too
            echo "board.name=UniFi Network Video Recorder"
            echo "board.shortname=UNVR";;
        'UNVR_PRO')
            echo "board.sysid=0xea20"
            echo "board.name=UniFi Network Video Recorder Pro"
            echo "board.shortname=UNVRPRO";;
        'MAC_OS')
            echo "board.sysid=0xffff"
            echo "board.name=UniFi Network Video Recorder"
            echo "board.shortname=UNVR";;
        'ENVR')
            echo "board.sysid=0xea3f"
            echo "board.name=UniFi Enterprise Network Video Recorder"
            echo "board.shortname=ENVR";;
        *)
            echo "ERROR: Unknown device '${DEVICE}'"
            exit 1;;
    esac

    # echo "board.sysid=0xea36" # UDMPROMAX - does not work
    # echo "board.sysid=0xea2a" # UDW - does not work
    # echo "board.sysid=0xe970" # UCK_G2_PLUS - does not work
    # echo "board.sysid=0xea13" # UDM_SE - does not work
    # echo "board.sysid=0xea15" # UDM_PRO - does not work
    # echo "board.sysid=0xa69a" # UCGMAX - does not work
    # echo "board.sysid=0xa6a8" # UCGFIBER - does not work
    # echo "board.sysid=0xa67a" # UDR7 - does not work
    # echo "board.sysid=0xb719" # UVC_NVR - old unifi-video
    # echo "board.sysid=0xea51" # UNAS_PRO - not applicable

    echo "board.subtype="
    echo "board.reboot=30"
    echo "board.upgrade=310"
    echo "board.cpu.id=00000000-00000000"
    echo "board.uuid=${uuid}"
    echo "board.bom=1"
    echo "board.hwrev=1"
    echo "board.serialno=${serial}"
    echo "board.qrid=sTpBUR"
fi
