on:
  workflow_dispatch:
  schedule:
    - cron: '40 3 * * *'
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: FW_EDGE=1 bash check-latest-firmware.sh
